import { useState, useEffect } from 'react';
import { useAuth } from '../contexts/AuthContext';
import { Sparkles, Heart, Bookmark, ArrowRight, Layers } from 'lucide-react';
import { getImageUrl } from '../lib/url';

export function ExploreFeed({ onRemix }) {
    const { user } = useAuth();
    const [feed, setFeed] = useState([]);
    const [loading, setLoading] = useState(true);
    const apiUrl = import.meta.env.VITE_API_URL || 'http://localhost:8787';

    useEffect(() => {
        const fetchFeed = async () => {
            try {
                const res = await fetch(`${apiUrl}/api/public/feed`);
                if (res.ok) {
                    const data = await res.json();
                    setFeed(data.feed || []);
                }
            } catch (e) {
                console.error("Failed to fetch feed:", e);
            } finally {
                setLoading(false);
            }
        };
        fetchFeed();
    }, [apiUrl]);

    const handleAction = (type, item) => {
        if (!user) {
            // Store action for post-login redirect
            localStorage.setItem('redirectAction', JSON.stringify({ type, id: item.id }));
            window.location.href = '/login'; // Or use a router if available
            return;
        }

        if (type === 'remix') {
            onRemix(item);
        } else {
            performInteraction(type, item.id);
        }
    };

    const performInteraction = async (type, id) => {
        try {
            const token = await user.getIdToken();
            const res = await fetch(`${apiUrl}/api/generations/${id}/${type}`, {
                method: 'POST',
                headers: { 'Authorization': `Bearer ${token}` }
            });
            if (res.ok) {
                // Optimistic UI update
                setFeed(prev => prev.map(item => {
                    if (item.id === id) {
                        const countKey = type === 'like' ? 'likesCount' : 'bookmarksCount';
                        const isSetKey = type === 'like' ? 'isLiked' : 'isBookmarked';
                        const currentCount = item[countKey] || 0;
                        const currentlySet = item[isSetKey];

                        return {
                            ...item,
                            [countKey]: currentlySet ? currentCount - 1 : currentCount + 1,
                            [isSetKey]: !currentlySet
                        };
                    }
                    return item;
                }));
            }
        } catch (e) {
            console.error(`Failed to ${type}:`, e);
        }
    };

    if (loading) {
        return (
            <div className="min-h-screen flex items-center justify-center">
                <div className="w-12 h-12 border-4 border-violet-500 border-t-transparent rounded-full animate-spin"></div>
            </div>
        );
    }

    return (
        <div className="w-full max-w-7xl mx-auto px-4 py-12">
            <div className="text-center mb-16 space-y-4 relative">
                {user && (
                    <button
                        onClick={() => window.location.href = '/'}
                        className="absolute left-0 top-0 flex items-center gap-2 text-slate-400 hover:text-white transition-colors text-sm font-medium bg-white/5 px-4 py-2 rounded-full border border-white/10 hover:bg-white/10"
                    >
                        <ArrowRight className="w-4 h-4 rotate-180" />
                        Back to Studio
                    </button>
                )}
                <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-violet-500/10 border border-violet-500/20 text-violet-400 text-sm font-medium animate-fade-in">
                    <Sparkles className="w-4 h-4" />
                    <span>Discovery Feed</span>
                </div>
                <h1 className="text-5xl md:text-6xl font-bold tracking-tight text-white">
                    Explore the <span className="bg-clip-text text-transparent bg-gradient-to-r from-violet-400 to-fuchsia-400">Masterpieces</span>
                </h1>
                <p className="text-gray-400 text-lg max-w-2xl mx-auto">
                    Generated by our community. Remix any style to create your own magic.
                </p>
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6">
                {feed.map((item) => (
                    <div
                        key={item.id}
                        className="group relative aspect-[3/4] rounded-2xl overflow-hidden bg-gray-900 border border-white/5 hover:border-violet-500/50 transition-all duration-500 hover:-translate-y-2 hover:shadow-2xl hover:shadow-violet-500/20"
                    >
                        <img
                            src={getImageUrl(item.imageUrl, apiUrl)}
                            onLoad={() => console.log('Image loaded:', getImageUrl(item.imageUrl, apiUrl))}
                            onError={() => console.error('Image FAILED:', { path: item.imageUrl, apiUrl, final: getImageUrl(item.imageUrl, apiUrl) })}
                            alt={item.summary}
                            className="w-full h-full object-cover transition-transform duration-700 group-hover:scale-110"
                        />

                        {/* Hover Overlay */}
                        <div className="absolute inset-0 bg-gradient-to-t from-black via-black/20 to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-300 flex flex-col justify-end p-6">
                            <div className="flex items-center justify-between mb-4">
                                <div className="flex gap-4 text-white font-medium">
                                    <button
                                        onClick={() => handleAction('like', item)}
                                        className="flex items-center gap-1.5 hover:text-rose-400 transition-colors"
                                    >
                                        <Heart className={`w-5 h-5 ${item.isLiked ? 'fill-rose-500 text-rose-500' : ''}`} />
                                        <span>{item.likesCount || 0}</span>
                                    </button>
                                    <button
                                        onClick={() => handleAction('bookmark', item)}
                                        className="flex items-center gap-1.5 hover:text-amber-400 transition-colors"
                                    >
                                        <Bookmark className={`w-5 h-5 ${item.isBookmarked ? 'fill-amber-500 text-amber-500' : ''}`} />
                                        <span>{item.bookmarksCount || 0}</span>
                                    </button>
                                </div>
                            </div>

                            <button
                                onClick={() => handleAction('remix', item)}
                                className="w-full py-3 bg-white text-black rounded-xl font-bold flex items-center justify-center gap-2 hover:bg-violet-500 hover:text-white transition-all duration-300 transform active:scale-95 shadow-xl"
                            >
                                <Layers className="w-5 h-5" />
                                <span>Remix with me</span>
                                <ArrowRight className="w-4 h-4 ml-1" />
                            </button>
                        </div>

                        {/* Content Bottom (Always visible or semi-visible) */}
                        <div className="absolute top-4 left-4 right-4 flex justify-between items-start pointer-events-none">
                            <div className="px-3 py-1 rounded-lg bg-black/40 backdrop-blur-md border border-white/10 text-[10px] uppercase tracking-wider font-bold text-white/80">
                                AI Masterpiece
                            </div>
                        </div>
                    </div>
                ))}
            </div>
        </div>
    );
}
