import { useState, useEffect } from 'react';
import { Sparkles, Download, Calendar, ThumbsUp, Share2, Eye, Share } from 'lucide-react';
import { getImageUrl } from '../lib/url';

export function ShareView({ genId }) {
    const [data, setData] = useState(null);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState(null);
    const [showShareMenu, setShowShareMenu] = useState(false);

    const apiUrl = import.meta.env.VITE_API_URL || 'http://localhost:8787';

    useEffect(() => {
        const fetchShare = async () => {
            try {
                const res = await fetch(`${apiUrl}/api/public/share/${genId}`);
                if (!res.ok) {
                    if (res.status === 404) throw new Error("This masterpiece is not public or does not exist.");
                    throw new Error("Failed to load masterpiece");
                }
                const json = await res.json();
                const fetchedData = json.generation || json;
                if (!fetchedData || !fetchedData.imageUrl) {
                    throw new Error("Invalid masterpiece data received");
                }
                setData(fetchedData);
            } catch (e) {
                setError(e.message);
            } finally {
                setLoading(false);
            }
        };
        fetchShare();
    }, [genId]);

    const handleDownload = async () => {
        if (!data) return;
        try {
            const url = getImageUrl(data.imageUrl, apiUrl);
            const res = await fetch(url);
            const blob = await res.blob();
            const downloadUrl = window.URL.createObjectURL(blob);
            const a = document.createElement('a');
            a.href = downloadUrl;
            a.download = `masterpiece-${genId}.png`;
            document.body.appendChild(a);
            a.click();
            window.URL.revokeObjectURL(url);
        } catch (e) {
            console.error("Download failed:", e);
        }
    };

    const handleCopyLink = async () => {
        try {
            await navigator.clipboard.writeText(window.location.href);
            alert("Link copied to clipboard!");
            setShowShareMenu(false);
        } catch (err) {
            console.error('Copy failed:', err);
        }
    };

    const handleNativeShare = async () => {
        const url = window.location.href;
        const title = data.summary || "My AI Masterpiece";
        const text = `Check out this AI masterpiece! Generated by Justin Generator.`;

        if (navigator.share) {
            try {
                await navigator.share({ title, text, url });
                setShowShareMenu(false);
            } catch (err) {
                if (err.name !== 'AbortError') console.error('Share failed:', err);
            }
        } else {
            handleCopyLink();
        }
    };

    if (loading) {
        return (
            <div className="min-h-screen flex flex-col items-center justify-center bg-theme-bg-primary gap-4">
                <div className="w-12 h-12 border-4 border-violet-500 border-t-transparent rounded-full animate-spin"></div>
                <p className="text-violet-500 animate-pulse font-medium">Revealing Masterpiece...</p>
            </div>
        );
    }

    if (error) {
        return (
            <div className="min-h-screen flex flex-col items-center justify-center bg-theme-bg-primary p-6 text-center">
                <div className="glass-panel p-8 rounded-3xl border-red-500/20 max-w-md w-full">
                    <div className="bg-red-500/10 p-4 rounded-full w-16 h-16 flex items-center justify-center mx-auto mb-6">
                        <Sparkles className="w-8 h-8 text-red-500" />
                    </div>
                    <h2 className="text-2xl font-bold text-theme-text-primary mb-2">Oops!</h2>
                    <p className="text-theme-text-secondary mb-8">{error}</p>
                    <button
                        onClick={() => window.location.href = '/'}
                        className="w-full bg-theme-bg-accent hover:bg-theme-glass-bg text-theme-text-primary font-bold py-3 px-6 rounded-xl transition-all border border-theme-glass-border"
                    >
                        Return Home
                    </button>
                </div>
            </div>
        );
    }

    return (
        <div className="min-h-screen w-full bg-theme-bg-primary flex flex-col items-center py-12 px-4 overflow-x-hidden">
            {/* Logo/Header */}
            <div
                className="flex items-center gap-3 mb-12 cursor-pointer group"
                onClick={() => window.location.href = '/'}
            >
                <div className="bg-violet-600 p-2 rounded-lg shadow-lg shadow-violet-500/30 group-hover:scale-110 transition-transform">
                    <Sparkles className="w-6 h-6 text-white" />
                </div>
                <h1 className="text-2xl font-bold text-theme-text-primary tracking-tight">Justin Generator</h1>
            </div>

            <div className="w-full max-w-2xl animate-fade-in pb-20">
                <div className="glass-card overflow-hidden rounded-[2.5rem] border-theme-glass-border shadow-2xl shadow-violet-500/5 group">
                    {/* Main Image Container */}
                    <div className="relative aspect-[3/4] bg-theme-bg-accent overflow-hidden">
                        <img
                            src={getImageUrl(data.imageUrl, apiUrl, 1200)}
                            alt={data.summary}
                            className="w-full h-full object-cover transition-transform duration-1000 group-hover:scale-105"
                            loading="lazy"
                            decoding="async"
                        />
                        <div className="absolute inset-0 bg-gradient-to-t from-black/60 via-transparent to-transparent opacity-60"></div>

                        {/* Action FABs */}
                        <div className="absolute top-6 right-6 flex flex-col gap-3">
                            <button
                                onClick={handleDownload}
                                className="p-4 bg-theme-glass-bg hover:bg-theme-bg-accent backdrop-blur-xl rounded-2xl border border-theme-glass-border text-theme-text-primary transition-all hover:scale-110 active:scale-95 group/btn shadow-xl"
                                title="Download Masterpiece"
                            >
                                <Download className="w-6 h-6 group-hover/btn:rotate-12 transition-transform" />
                            </button>
                            <div className="relative">
                                <button
                                    onClick={() => setShowShareMenu(!showShareMenu)}
                                    className="p-4 bg-violet-600/10 hover:bg-violet-600/20 backdrop-blur-xl rounded-2xl border border-violet-500/30 text-violet-500 transition-all hover:scale-110 active:scale-95 group/btn shadow-xl"
                                    title="Share Masterpiece"
                                >
                                    <Share2 className="w-6 h-6 group-hover/cta:scale-110 transition-transform" />
                                </button>

                                {showShareMenu && (
                                    <div className="absolute top-full right-0 mt-2 w-48 bg-theme-bg-accent border border-theme-glass-border rounded-2xl shadow-2xl backdrop-blur-2xl z-50 overflow-hidden animate-in slide-in-from-top-2 duration-200">
                                        <button onClick={handleCopyLink} className="w-full px-4 py-3 flex items-center gap-3 text-sm font-bold text-theme-text-primary hover:bg-white/5 transition-colors text-left">
                                            <Share className="w-4 h-4 text-violet-400" /> Copy Link
                                        </button>
                                        <button onClick={handleNativeShare} className="w-full px-4 py-3 flex items-center gap-3 text-sm font-bold text-theme-text-primary hover:bg-white/5 transition-colors text-left border-t border-theme-glass-border">
                                            <Share2 className="w-4 h-4 text-violet-400" /> Share via...
                                        </button>
                                    </div>
                                )}
                            </div>
                        </div>
                    </div>

                    {/* Metadata Section */}
                    <div className="p-8 md:p-10 space-y-8">
                        <div className="flex flex-col md:flex-row md:items-end justify-between gap-6">
                            <div className="space-y-4">
                                <h2 className="text-4xl font-black text-theme-text-primary leading-tight">
                                    {data.summary}
                                </h2>
                                <div className="flex items-center gap-4">
                                    <div className="flex items-center gap-1.5 text-theme-text-muted">
                                        <Eye size={14} className="text-violet-400" />
                                        <span className="text-xs font-bold uppercase tracking-widest">{data.views || 0} Views</span>
                                    </div>
                                    <div className="w-1 h-1 rounded-full bg-theme-glass-border"></div>
                                    <div className="flex items-center gap-1.5 text-theme-text-muted">
                                        <Calendar size={14} className="text-violet-400" />
                                        <span className="text-xs font-bold uppercase tracking-widest">{new Date(data.createdAt).toLocaleDateString()}</span>
                                    </div>
                                </div>
                            </div>

                            <div className="flex items-center gap-2 bg-theme-bg-accent p-1.5 rounded-2xl border border-theme-glass-border shadow-inner">
                                <div className="px-6 py-3 text-center">
                                    <p className="text-[10px] text-theme-text-muted font-bold uppercase tracking-widest mb-1">Impact</p>
                                    <div className="flex items-center gap-2 justify-center">
                                        <ThumbsUp className="w-5 h-5 text-emerald-500 fill-emerald-500/10" />
                                        <span className="text-2xl font-black text-theme-text-primary">{data.votes || 0}</span>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div className="h-px w-full bg-gradient-to-r from-transparent via-theme-glass-border to-transparent"></div>

                        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                            <button
                                onClick={() => {
                                    localStorage.setItem('redirectAction', JSON.stringify({ type: 'remix', id: genId }));
                                    window.location.href = '/';
                                }}
                                className="flex-1 bg-gradient-to-br from-violet-600 to-fuchsia-600 hover:from-violet-500 hover:to-fuchsia-500 text-white font-black py-5 px-8 rounded-2xl transition-all shadow-xl shadow-violet-600/20 active:scale-[0.98] flex items-center justify-center gap-3 border border-white/10 group/cta"
                            >
                                <span className="text-lg">Remix Me</span>
                                <Sparkles className="w-5 h-5 group-hover/cta:animate-pulse" />
                            </button>

                            <button
                                onClick={handleNativeShare}
                                className="flex-1 bg-theme-bg-accent hover:bg-theme-glass-bg text-theme-text-primary font-black py-5 px-8 rounded-2xl transition-all border border-theme-glass-border flex items-center justify-center gap-3 group/share"
                            >
                                <span className="text-lg">Share with Friends</span>
                                <Share2 className="w-5 h-5 text-violet-400 group-hover/share:scale-110 transition-transform" />
                            </button>
                        </div>
                    </div>
                </div>

                {/* Viral Encouragement */}
                <div className="mt-8 text-center space-y-4">
                    <p className="text-theme-text-secondary text-sm font-medium italic">
                        "Your image, your rules. No prompts exposed, just pure magic."
                    </p>
                    <div className="flex items-center justify-center gap-2 text-theme-text-muted text-[10px] font-bold uppercase tracking-widest">
                        <Sparkles size={10} className="text-violet-500" />
                        POWERED BY JUSTIN GENERATOR
                        <Sparkles size={10} className="text-violet-500" />
                    </div>
                </div>
            </div>
        </div>
    );
}
